import React, { useState } from 'react';
import {
  Code2, Server, Copy, CheckCircle2, Download,
  Globe, Info, Package,
} from 'lucide-react';

// ── Artifact generators ───────────────────────────────────────────────────────

function getPackageDeps(project) {
  const llm = project.llmConfig ?? {};
  const nodeTypes = new Set((project.pipeline?.nodes ?? []).map((n) => n.type));
  const chat = llm.chatProvider ?? 'openai';
  const embed = llm.embeddingProvider ?? 'openai';

  const deps = new Set([
    'fastapi==0.115.0',
    'uvicorn[standard]==0.30.0',
    'python-dotenv==1.0.0',
    'langchain==0.3.0',
    'langchain-core==0.3.0',
    'pydantic==2.9.0',
  ]);

  if (chat === 'openai' || embed === 'openai') { deps.add('langchain-openai==0.2.0'); deps.add('openai==1.50.0'); }
  if (chat === 'google' || embed === 'google') { deps.add('langchain-google-genai==2.0.0'); deps.add('google-generativeai==0.8.0'); }
  if (chat === 'anthropic')                    { deps.add('langchain-anthropic==0.2.0'); deps.add('anthropic==0.36.0'); }
  if (chat === 'cohere' || embed === 'cohere') { deps.add('langchain-cohere==0.3.0'); deps.add('cohere==5.11.0'); }
  if (chat === 'mistral')                      { deps.add('langchain-mistralai==0.2.0'); }
  if (chat === 'ollama' || embed === 'ollama') { deps.add('langchain-ollama==0.2.0'); deps.add('ollama==0.3.0'); }
  if (embed === 'huggingface')                 { deps.add('langchain-huggingface==0.1.0'); deps.add('sentence-transformers==3.2.0'); }

  if (nodeTypes.has('VectorStore'))       { deps.add('langchain-qdrant==0.1.4'); deps.add('qdrant-client==1.12.0'); }
  if (nodeTypes.has('ChromaDBStore'))     { deps.add('langchain-chroma==0.1.4'); deps.add('chromadb==0.5.0'); }
  if (nodeTypes.has('Reranker'))          { deps.add('flashrank==0.2.9'); }
  if (nodeTypes.has('CohereRerank'))      { deps.add('cohere==5.11.0'); }
  if (nodeTypes.has('OCRProcessor'))      { deps.add('pytesseract==0.3.13'); deps.add('Pillow==10.4.0'); }
  if (nodeTypes.has('DocumentExtraction')){ deps.add('unstructured==0.16.0'); }
  if (nodeTypes.has('MarkdownConverter')) { deps.add('markdownify==0.13.1'); }

  return [...deps];
}

function getEnvVars(project) {
  const llm = project.llmConfig ?? {};
  const chat = llm.chatProvider ?? 'openai';
  const embed = llm.embeddingProvider ?? 'openai';
  const vars = [];
  if (chat === 'openai'    || embed === 'openai')    vars.push({ key: 'OPENAI_API_KEY',    hint: 'sk-...' });
  if (chat === 'google'    || embed === 'google')    vars.push({ key: 'GOOGLE_API_KEY',    hint: 'AIza...' });
  if (chat === 'anthropic')                          vars.push({ key: 'ANTHROPIC_API_KEY', hint: 'sk-ant-...' });
  if (chat === 'cohere'    || embed === 'cohere')    vars.push({ key: 'COHERE_API_KEY',    hint: 'your_cohere_key' });
  if (chat === 'mistral')                            vars.push({ key: 'MISTRAL_API_KEY',   hint: 'your_mistral_key' });
  vars.push({ key: 'PROJECT_ID', hint: project.id });
  return vars;
}

function buildDockerfile(project) {
  const llm = project.llmConfig ?? {};
  const envVars = getEnvVars(project);
  return `# Dockerfile — ${project.name}
# LLM: ${llm.chatModel ?? 'gpt-4o'} (${llm.chatProvider ?? 'openai'})
# Embedding: ${llm.embeddingModel ?? 'text-embedding-3-small'} (${llm.embeddingProvider ?? 'openai'})
# Generated by Visual RAG Builder

FROM python:3.11-slim

WORKDIR /app

# System dependencies
RUN apt-get update && apt-get install -y \\
    build-essential curl \\
    && rm -rf /var/lib/apt/lists/*

# Python dependencies
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Application code
COPY . .

# API keys — replace with actual values or pass via --env-file
${envVars.map((v) => `ENV ${v.key}=${v.hint}`).join('\n')}

EXPOSE 8000

CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]
`;
}

function buildDockerCompose(project) {
  const nodeTypes = new Set((project.pipeline?.nodes ?? []).map((n) => n.type));
  const needsQdrant = nodeTypes.has('VectorStore');
  const envVars = getEnvVars(project);

  const appService = `  app:
    build: .
    ports:
      - "8000:8000"
    environment:
${envVars.map((v) => `      - ${v.key}=\${${v.key}}`).join('\n')}${needsQdrant ? '\n    depends_on:\n      - qdrant' : ''}
    restart: unless-stopped`;

  const qdrantService = needsQdrant ? `\n\n  qdrant:
    image: qdrant/qdrant:latest
    ports:
      - "6333:6333"
    volumes:
      - qdrant_data:/qdrant/storage
    restart: unless-stopped` : '';

  const volumes = needsQdrant ? '\n\nvolumes:\n  qdrant_data:' : '';

  return `# docker-compose.yml — ${project.name}
# Generated by Visual RAG Builder

version: "3.9"

services:
${appService}${qdrantService}${volumes}
`;
}

function buildRequirements(project) {
  return getPackageDeps(project).join('\n');
}

const IMAGE = 'ghcr.io/visual-rag-builder/rag-engine:latest';

function buildDockerRunCmd(project) {
  const envVars = getEnvVars(project);
  const envFlags = envVars.map((v) => `  -e ${v.key}=${v.hint} \\`).join('\n');
  return `docker run -d \\
  --name rag-engine \\
  -p 8000:8000 \\
${envFlags}
  -v $(pwd)/pipeline.json:/app/pipeline.json \\
  ${IMAGE}`;
}

function buildRunScript(project) {
  const envVars = getEnvVars(project);
  const envFlags = envVars.map((v) => `  -e ${v.key}=\${${v.key}:-${v.hint}} \\`).join('\n');
  return `#!/bin/bash
# run.sh — ${project.name}
# Generated by Visual RAG Builder

IMAGE="${IMAGE}"

echo "Pulling image..."
docker pull $IMAGE

echo "Starting RAG engine..."
docker run -d \\
  --name rag-engine \\
  -p 8000:8000 \\
${envFlags}
  -v $(pwd)/pipeline.json:/app/pipeline.json \\
  $IMAGE

echo "Done! API running at http://localhost:8000"
echo "Health check: curl http://localhost:8000/health"
`;
}

function buildEnvFile(project) {
  const envVars = getEnvVars(project);
  return `# .env — ${project.name}
# Generated by Visual RAG Builder
# Fill in your actual API keys before running

${envVars.map((v) => `${v.key}=${v.hint}`).join('\n')}
`;
}

function buildPipelineJson(project) {
  return JSON.stringify(project.pipeline ?? {}, null, 2);
}

// ── Small helpers ─────────────────────────────────────────────────────────────

function useCopy() {
  const [key, setKey] = useState(null);
  const copy = (text, k) => {
    navigator.clipboard.writeText(text).catch(() => {});
    setKey(k);
    setTimeout(() => setKey(null), 2000);
  };
  return [key, copy];
}

function download(filename, content) {
  const blob = new Blob([content], { type: 'text/plain' });
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url; a.download = filename; a.click();
  URL.revokeObjectURL(url);
}

// ── Sub-components ────────────────────────────────────────────────────────────

function SectionHeader({ icon: IconComponent, iconBg, iconColor, title, description }) {
  return (
    <div className="flex items-start space-x-4 mb-5">
      <div className={`w-10 h-10 ${iconBg} rounded-xl flex items-center justify-center flex-shrink-0`}>
        {React.createElement(IconComponent, { size: 18, className: iconColor })}
      </div>
      <div>
        <h3 className="text-sm font-semibold text-gray-900">{title}</h3>
        <p className="text-xs text-gray-400 mt-0.5 leading-snug">{description}</p>
      </div>
    </div>
  );
}

function CopyBar({ label, value, copiedKey, copyKey, onCopy, onDownload, filename }) {
  const isCopied = copiedKey === copyKey;
  return (
    <div className="flex items-center space-x-2">
      {label && <span className="text-xs text-gray-500 font-medium">{label}</span>}
      <button
        onClick={() => onCopy(value, copyKey)}
        className={`flex items-center space-x-1.5 px-3 py-1.5 text-xs font-medium rounded-lg border transition-colors ${
          isCopied
            ? 'bg-emerald-50 border-emerald-200 text-emerald-700'
            : 'bg-white border-gray-200 text-gray-600 hover:bg-gray-50'
        }`}
      >
        {isCopied ? <CheckCircle2 size={12} /> : <Copy size={12} />}
        <span>{isCopied ? 'Copied!' : 'Copy'}</span>
      </button>
      {onDownload && (
        <button
          onClick={() => onDownload(filename, value)}
          className="flex items-center space-x-1.5 px-3 py-1.5 text-xs font-medium rounded-lg border border-gray-200 bg-white text-gray-600 hover:bg-gray-50 transition-colors"
        >
          <Download size={12} />
          <span>Download</span>
        </button>
      )}
    </div>
  );
}

function CodeBlock({ code, copiedKey, copyKey, onCopy, onDownload, filename }) {
  return (
    <div className="rounded-xl overflow-hidden border border-gray-200">
      <div className="flex items-center justify-between bg-gray-800 px-4 py-2">
        <span className="text-xs text-gray-400 font-mono">{filename}</span>
        <CopyBar
          value={code}
          copiedKey={copiedKey}
          copyKey={copyKey}
          onCopy={onCopy}
          onDownload={onDownload}
          filename={filename}
        />
      </div>
      <pre className="bg-gray-900 text-gray-100 text-xs font-mono p-4 overflow-x-auto leading-relaxed whitespace-pre">
        {code}
      </pre>
    </div>
  );
}

function InfoBanner({ children }) {
  return (
    <div className="flex items-start space-x-2 p-3 bg-amber-50 rounded-xl border border-amber-200 mt-4">
      <Info size={13} className="text-amber-500 flex-shrink-0 mt-0.5" />
      <p className="text-xs text-amber-700 leading-snug">{children}</p>
    </div>
  );
}

// ── Main component ────────────────────────────────────────────────────────────

const DOCKER_TABS = [
  { id: 'dockerfile',   label: 'Dockerfile' },
  { id: 'compose',      label: 'docker-compose.yml' },
  { id: 'requirements', label: 'requirements.txt' },
];

const IMAGE_TABS = [
  { id: 'run',      label: 'run.sh' },
  { id: 'env',      label: '.env' },
  { id: 'pipeline', label: 'pipeline.json' },
];

export default function ProjectDeployTab({ project }) {
  const [copiedKey, copy] = useCopy();
  const [iframeWidth, setIframeWidth] = useState('100%');
  const [iframeHeight, setIframeHeight] = useState(600);
  const [dockerTab, setDockerTab] = useState('dockerfile');
  const [imageTab, setImageTab] = useState('run');

  const baseUrl = window.location.origin;
  const shareUrl  = `${baseUrl}/share/${project.id}`;
  const embedUrl  = `${baseUrl}/embed/${project.id}`;
  const iframeCode = `<iframe\n  src="${embedUrl}"\n  width="${iframeWidth}"\n  height="${iframeHeight}px"\n  style="border:none; border-radius:12px;"\n  title="RAG Chat: ${project.name}"\n  allow="clipboard-write"\n></iframe>`;

  const dockerfile    = buildDockerfile(project);
  const dockerCompose = buildDockerCompose(project);
  const requirements  = buildRequirements(project);

  const pullCmd        = `docker pull ${IMAGE}`;
  const dockerRunCmd   = buildDockerRunCmd(project);
  const runScript      = buildRunScript(project);
  const envFile        = buildEnvFile(project);
  const pipelineJson   = buildPipelineJson(project);
  const imageContent   = { run: runScript, env: envFile, pipeline: pipelineJson };
  const imageFilenames = { run: 'run.sh', env: '.env', pipeline: 'pipeline.json' };

  const dockerContent = { dockerfile, compose: dockerCompose, requirements };
  const dockerFilenames = { dockerfile: 'Dockerfile', compose: 'docker-compose.yml', requirements: 'requirements.txt' };

  return (
    <div className="flex-1 overflow-auto bg-gray-50 p-8">
      <div className="max-w-3xl mx-auto space-y-6">

        {/* Page heading */}
        <div>
          <h2 className="text-base font-semibold text-gray-900">Deploy</h2>
          <p className="text-sm text-gray-500 mt-0.5">
            Choose how to share or host your RAG pipeline.
          </p>
        </div>

        {/* ── 1. Share Link ─────────────────────────────────────────────── */}
        <div className="bg-white rounded-2xl border border-gray-200 p-6">
          <SectionHeader
            icon={Globe}
            iconBg="bg-indigo-50"
            iconColor="text-indigo-600"
            title="Share Link"
            description="Anyone with this link can open your RAG chat interface in their browser."
          />

          <div className="flex items-center space-x-2">
            <input
              readOnly
              value={shareUrl}
              className="flex-1 border border-gray-200 rounded-xl px-3.5 py-2.5 text-sm text-gray-600 bg-gray-50 font-mono focus:outline-none"
            />
            <CopyBar
              value={shareUrl}
              copiedKey={copiedKey}
              copyKey="share"
              onCopy={copy}
            />
          </div>

          <InfoBanner>
            This link requires your RAG backend to be running and publicly accessible.
            Deploy the backend first, then share this URL with your users.
          </InfoBanner>
        </div>

        {/* ── 2. Embed (iFrame) ─────────────────────────────────────────── */}
        <div className="bg-white rounded-2xl border border-gray-200 p-6">
          <SectionHeader
            icon={Code2}
            iconBg="bg-violet-50"
            iconColor="text-violet-600"
            title="Embed (iFrame)"
            description="Paste this snippet into any webpage to embed your RAG chat widget."
          />

          {/* Customisation controls */}
          <div className="flex items-center space-x-4 mb-4">
            <div>
              <label className="block text-xs font-semibold text-gray-500 mb-1">Width</label>
              <input
                value={iframeWidth}
                onChange={(e) => setIframeWidth(e.target.value)}
                placeholder="100% or 800"
                className="w-28 border border-gray-200 rounded-lg px-2.5 py-1.5 text-xs text-gray-700 focus:outline-none focus:ring-2 focus:ring-violet-400"
              />
            </div>
            <div>
              <label className="block text-xs font-semibold text-gray-500 mb-1">Height (px)</label>
              <input
                type="number"
                value={iframeHeight}
                onChange={(e) => setIframeHeight(Number(e.target.value))}
                className="w-24 border border-gray-200 rounded-lg px-2.5 py-1.5 text-xs text-gray-700 focus:outline-none focus:ring-2 focus:ring-violet-400"
              />
            </div>
          </div>

          <CodeBlock
            code={iframeCode}
            copiedKey={copiedKey}
            copyKey="iframe"
            onCopy={copy}
            filename="embed.html"
          />

          <InfoBanner>
            The embed URL must be served over HTTPS in production for browsers to allow iFrame embedding.
          </InfoBanner>
        </div>

        {/* ── 3. Dockerfile / Self-host ─────────────────────────────────── */}
        <div className="bg-white rounded-2xl border border-gray-200 p-6">
          <SectionHeader
            icon={Server}
            iconBg="bg-teal-50"
            iconColor="text-teal-600"
            title="Self-Host with Docker"
            description="Generated from your pipeline configuration — LLM provider, embedding model, and node types."
          />

          {/* Detected config chips */}
          <div className="flex flex-wrap gap-2 mb-5">
            {[
              { label: `LLM: ${project.llmConfig?.chatModel ?? 'gpt-4o'}`, color: 'bg-purple-50 text-purple-700 border-purple-200' },
              { label: `Embed: ${project.llmConfig?.embeddingModel ?? 'text-embedding-3-small'}`, color: 'bg-indigo-50 text-indigo-700 border-indigo-200' },
              { label: `${project.pipeline?.nodes?.length ?? 0} nodes`, color: 'bg-gray-100 text-gray-600 border-gray-200' },
            ].map((chip) => (
              <span key={chip.label} className={`text-xs font-medium px-2.5 py-1 rounded-full border ${chip.color}`}>
                {chip.label}
              </span>
            ))}
          </div>

          {/* File tabs */}
          <div className="flex items-center border-b border-gray-100 mb-4 space-x-1">
            {DOCKER_TABS.map((t) => (
              <button
                key={t.id}
                onClick={() => setDockerTab(t.id)}
                className={`px-3 py-2 text-xs font-medium rounded-t-lg transition-colors border-b-2 -mb-px ${
                  dockerTab === t.id
                    ? 'border-teal-500 text-teal-700 bg-teal-50'
                    : 'border-transparent text-gray-500 hover:text-gray-700 hover:bg-gray-50'
                }`}
              >
                {t.label}
              </button>
            ))}
          </div>

          <CodeBlock
            code={dockerContent[dockerTab]}
            copiedKey={copiedKey}
            copyKey={`docker-${dockerTab}`}
            onCopy={copy}
            onDownload={download}
            filename={dockerFilenames[dockerTab]}
          />

          {/* Env var reminder */}
          <div className="mt-4 bg-gray-50 rounded-xl border border-gray-200 p-4">
            <p className="text-xs font-semibold text-gray-600 mb-2">Required environment variables</p>
            <div className="space-y-1.5">
              {getEnvVars(project).map((v) => (
                <div key={v.key} className="flex items-center space-x-2 text-xs font-mono">
                  <span className="text-indigo-600 font-semibold">{v.key}</span>
                  <span className="text-gray-400">=</span>
                  <span className="text-gray-500">{v.hint}</span>
                </div>
              ))}
            </div>
            <p className="text-[11px] text-gray-400 mt-3">
              Pass these via <code className="bg-gray-200 px-1 rounded">--env-file .env</code> or set them in your cloud provider's environment config.
            </p>
          </div>

          <InfoBanner>
            Download all three files into the same directory as your RAG backend code, then run{' '}
            <code className="bg-amber-100 px-1 rounded font-mono">docker compose up --build</code> to start.
          </InfoBanner>
        </div>

        {/* ── 4. Pre-built Docker Image ──────────────────────────────────── */}
        <div className="bg-white rounded-2xl border border-gray-200 p-6">
          <SectionHeader
            icon={Package}
            iconBg="bg-amber-50"
            iconColor="text-amber-600"
            title="Pre-built Docker Image"
            description="Pull a ready-to-run image — no build step required. Mount your pipeline config and set API keys."
          />

          {/* Pull command */}
          <p className="text-xs font-semibold text-gray-600 mb-2">Pull the image</p>
          <div className="flex items-center space-x-2 mb-5">
            <input
              readOnly
              value={pullCmd}
              className="flex-1 border border-gray-200 rounded-xl px-3.5 py-2.5 text-sm text-gray-600 bg-gray-50 font-mono focus:outline-none"
            />
            <CopyBar
              value={pullCmd}
              copiedKey={copiedKey}
              copyKey="pull"
              onCopy={copy}
            />
          </div>

          {/* Run command */}
          <p className="text-xs font-semibold text-gray-600 mb-2">Run command</p>
          <CodeBlock
            code={dockerRunCmd}
            copiedKey={copiedKey}
            copyKey="docker-run"
            onCopy={copy}
            filename="terminal"
          />

          {/* Downloadable files */}
          <p className="text-xs font-semibold text-gray-600 mt-5 mb-2">Download helper files</p>
          <div className="flex items-center border-b border-gray-100 mb-4 space-x-1">
            {IMAGE_TABS.map((t) => (
              <button
                key={t.id}
                onClick={() => setImageTab(t.id)}
                className={`px-3 py-2 text-xs font-medium rounded-t-lg transition-colors border-b-2 -mb-px ${
                  imageTab === t.id
                    ? 'border-amber-500 text-amber-700 bg-amber-50'
                    : 'border-transparent text-gray-500 hover:text-gray-700 hover:bg-gray-50'
                }`}
              >
                {t.label}
              </button>
            ))}
          </div>

          <CodeBlock
            code={imageContent[imageTab]}
            copiedKey={copiedKey}
            copyKey={`image-${imageTab}`}
            onCopy={copy}
            onDownload={download}
            filename={imageFilenames[imageTab]}
          />

          <InfoBanner>
            To transfer the image offline: <code className="bg-amber-100 px-1 rounded font-mono">docker save {IMAGE} | gzip &gt; rag-engine.tar.gz</code>
            {' '}then load on another machine with: <code className="bg-amber-100 px-1 rounded font-mono">docker load &lt; rag-engine.tar.gz</code>
          </InfoBanner>
        </div>

      </div>
    </div>
  );
}
